### ISSUE TITLE
Error when running the example

### ISSUE THREAD

**Issue by kyleliang919** [google/unrestricted-adversarial-examples#53]
AttributeError: 'ImageFolderWithFilenames' object has no attribute 'samples'.
I am also looking into the issue, but I am kind of clueless. Does anybody else have the same problem?

Below is the full trace.

 /anaconda/envs/py35/lib/python3.5/site-packages/h5py/__init__.py:36:

 FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-10-08 19:25:41.909854: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-08 19:25:46.158794: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-10-08 19:25:46.158860: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: kk80
2018-10-08 19:25:46.158882: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: kk80
2018-10-08 19:25:46.158944: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 390.30.0
2018-10-08 19:25:46.159004: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 390.30.0
2018-10-08 19:25:46.159025: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 390.30.0
Verification of dataset successful. Dataset is correctly prepared.
Verification of dataset successful. Dataset is correctly prepared.
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    model_name='undefended_keras_resnet')
  File "/home/pdimage/notebooks/Semantic_AdvGAN/imagenet/unrestricted-adversarial-examples/unrestricted-advex/unrestricted_advex/eval_kit.py", line 290, in evaluate_bird_or_bicycle_model
    label_to_examples=_get_bird_or_bicycle_label_to_examples(),
  File "/home/pdimage/notebooks/Semantic_AdvGAN/imagenet/unrestricted-adversarial-examples/unrestricted-advex/unrestricted_advex/eval_kit.py", line 243, in _get_bird_or_bicycle_label_to_examples
    for x_np, y_np, _ in dataset_iter:
  File "/home/pdimage/notebooks/Semantic_AdvGAN/imagenet/unrestricted-adversarial-examples/bird-or-bicycle/bird_or_bicycle/iterator.py", line 53, in <genexpr>
    dataset_iter = ((x_batch.numpy(), y_batch.numpy(), image_ids)
  File "/anaconda/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 259, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/anaconda/envs/py35/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 259, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/pdimage/notebooks/Semantic_AdvGAN/imagenet/unrestricted-adversarial-examples/bird-or-bicycle/bird_or_bicycle/iterator.py", line 18, in __getitem__
    path, _ = self.samples[index]
AttributeError: 'ImageFolderWithFilenames' object has no attribute 'samples

**Comment by nottombrown** [comment]
What version of pytorch are you using?

**Comment by kyleliang919** [comment]
I am using keras, not pytorch,  tensorflow 1.9.0

**Comment by nottombrown** [comment]
We install torchvision as a dependency. If you do `pip freeze | grep torch`
what is your output?

**Comment by nottombrown** [comment]
Closing this due to inactivity. Please reopen if this issue continues.

**Comment by YinYangOfDao** [comment]
> Closing this due to inactivity. Please reopen if this issue continues.

I have the same issue. I used
pytorch                   0.4.1            py36ha74772b_0  
torchvision               0.2.0            py36h17b6947_1    pytorch
